### ISSUE TITLE
[BUG] TrashCan does not work on server

### ISSUE THREAD

**Issue by lightlessfilms** [virtuaCode/valheim-mods#1]
Hi,

The Trashcan plugin does not fully work on servers.
I can see the trashcan icon on the right, but when I click an item on the trashcan it doesn't get disposed.

On a single player world this plugin works as intended.

**Comment by virtuaCode** [comment]
Thanks for your bug report. It would be nice if you can give me more info about your setup to let me reproduce the problem.

For example:

- Operating System
- Other Mods Installed
- Fullscreen/Window Mode
- Resolution

Btw the plugin should not be installed on the server. It's a client mod.

**Comment by lightlessfilms** [comment]
This issue can be closed. Somehow it works now.
My apologies for the late response.
