### ISSUE TITLE
Equipwheel/More Equipwheel - Not displaying any items after Valheim Patch 0.216.9

### ISSUE THREAD

**Issue by SaltiDawg** [virtuaCode/valheim-mods#12]
Believe the addon might need a tweak after Valheim Patch 0.216.9. The wheels display but they are all empty even though items exist in config locations.

Sorry not more details but have to reach out to many authors with base communications.

**Comment by SaltiDawg** [comment]
[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.OnEnable () (at <734fe4238e1145f5aa590071dc0d19a6>:0)
UnityEngine.GameObject:AddComponent()
EquipWheel.EquipGui:Awake()
UnityEngine.GameObject:AddComponent()
EquipWheel.Patcher:Awake_Postfix()
Player:DMD<Player::Awake>(Player)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
Game:DMD<Game::SpawnPlayer>(Game, Vector3)
Game:UpdateRespawn(Single)
Game:FixedUpdate()

[Info   :EquipWheel] Spawned EquipGui!
[Info   : Unity Log] 06/13/2023 12:14:10: Skipping unloading unused assets

[Info   : Unity Log] 06/13/2023 12:14:10: Minimap: Adding unique location (-2.5, 44.9, -4.0)

[Info   : Unity Log] 06/13/2023 12:14:10: Minimap: Adding unique location (-1099.5, 32.1, -1389.6)

[Info   : Unity Log] 06/13/2023 12:14:12: Starting music meadows

[Info   : Unity Log] 06/13/2023 12:14:12: Resumed music meadows at 0

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.OnEnable () (at <734fe4238e1145f5aa590071dc0d19a6>:0)
UnityEngine.GameObject:SetActive(Boolean)
EquipWheel.EquipGui:Update()

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

[Error  : Unity Log] MissingFieldException: Field 'ItemDrop/ItemData.m_equiped' not found.
Stack trace:
EquipWheel.EquipWheelUI.Update () (at <734fe4238e1145f5aa590071dc0d19a6>:0)

**Comment by ImOnMars** [comment]
Also now the auto-equip shield doesn't work either
