### ISSUE TITLE
The state of EquipWheel with Controllers

### ISSUE THREAD

**Issue by jbrown1597** [virtuaCode/valheim-mods#19]
You are a god for making this mod. Thank you.
On paper, it's a must have for me.

In practice though, it's been (*constructively) a learning curve.
There seems to be no ONE perfect setup to use with a controller - each config setup having slight compromises. 

> **I propose a simple solution:** 

Instead of trying to use buttons that are already mapped with multiple functions (X, B, LB, RS, etc),

Allow Equipwheel to be mapped to the D-pad (right & left) - essentially replacing the vanilla right-to-left scrolling, with Equipwheel.

If this mod aims to replace hotbar scrolling with a wheel - it just seems natural that you would use the same button for EquipWheel as you would to scroll. 
 
It would mean a lot <3 
Thanks again!

**Comment by virtuaCode** [comment]
Hey @jbrown1597,

I am currently working on a new version that will use the D-Pad as a Hotkey for the EquipWheel. 
Thanks for sharing your advice.

**Comment by virtuaCode** [comment]
The new version 1.5.0 (EquipWheel) now uses the LEFT or RIGHT button on the D-Pad for opening the wheel.
