### ISSUE TITLE
[Equip Wheel] Better filtering for item categories

### ISSUE THREAD

**Issue by Spirevipp** [virtuaCode/valheim-mods#20]
First of all, just want to say that this is a great mod and i love using it.

Is it possible to add better categories or wildcard filtering for item categories?

example, i want to have an equip wheel for my tools, but tools like axe and pickaxe fall into one handed and two handed weapon category.
this could be solved by splitting those categories into types like axes, swords, pickaxes, spears etc.
it could also be solved by allowing wildcard filters in the item name blacklist / whitelist.
if i want just axes i could do *Axe etc.
it would also be nice if mead was its own category, or wildcard *Mead

thanks for the great mod!

**Comment by virtuaCode** [comment]
The new mod version of EquipWheel v1.5.0 now supports regex filtering. You have to enable `ItemFiltering = true` in the config.
For example you can use `ItemRegex = axe|mead` for filtering items. Also blacklisting/ignoring items is possible with `ItemRegexIgnore`.
