### ISSUE TITLE
Left/Right controller binding change in EquipWheel causes gameplay issues

### ISSUE THREAD

**Issue by derekcannon** [virtuaCode/valheim-mods#21]
Recent changes have created usability issues for controller users. If left or right is assigned to the action wheel, a controller user can no longer use the native controller implementation of the quick inventory slots (e.g. using left/right d-pad + up). Sometimes it's helpful, for example, with health pots to have them pre-selected (using left/right d-pad) for quick usage (i.e. just pressing up on the d-pad).

(Also, personal preference here: the previous bindings felt better to use (button + left joystick.)

The only problem I personally experienced with X for the action button menu was sometimes it would equip a weapon AND sit the character down. I'd rather the sit button was disabled altogether rather than having the chance that the character sometimes randomly sits.

Either way, it'd be much appreciated if you could give us the option to use X instead of left/right d-pad buttons, as we could before.

**Comment by Snayler** [comment]
> The only problem I personally experienced with X for the action button menu was sometimes it would equip a weapon AND sit the character down. I'd rather the sit button was disabled altogether rather than having the chance that the character sometimes randomly sits.

Easily solvable by adding a similar setting as "IgnoreJoystickDuration" but for X button.

**Comment by virtuaCode** [comment]
The new version 1.5.1 uses the "Use"-Button as the default hotkey. In the config you have to change `HotkeyDPad` to `None`.

**Comment by derekcannon** [comment]
Thanks for the quick fix! This introduces a new issue though: now if you have a hammer selected and are on a resource you can't believe (e.g. no workbench), you can't get to the build menu to select a different item to build.

I assume this is because the code is assuming if there is nothing to interact with and the user presses A, trigger the equipment wheel? Mapping the action wheel back to X (sit button) might make the most sense.

**Comment by virtuaCode** [comment]
Sorry, I'm unable to reproduce your issue. Can you maybe upload a short video to youtube and post it here? And have you tested a different Controller Layout? I assume you are using the Classic Layout.

**Comment by derekcannon** [comment]
Thanks for adding the sit button binding back. Works perfectly now!

In regard to the previous bug encounter, I tried to reproduce it and I cannot. It happened after I died though, so maybe there's some edge case with that. I also have a few other mods enabled, so it could be some combination of them as well.


But either way, I'm using the sit button binding now and I'm very happy with that. So this issue can be closed if no one else is experiencing it.

Thanks again!
