### ISSUE TITLE
1.5.1 Is using A button instead of the intended X button

### ISSUE THREAD

**Issue by Snayler** [virtuaCode/valheim-mods#23]
Description says it all, unsure if it's just me or a coding mistake on the release.

EDIT: I just noticed X can be Use on the console layouts, I'm using Classic Layout hence the confusion.

**Comment by virtuaCode** [comment]
What controller are you using? On XBox controllers it's the X-Button.

**Comment by Snayler** [comment]
I'm using an XBox controller, but with the classic layout, that's why I was confused with the changelog

**Comment by virtuaCode** [comment]
Sorry I only tested for the "Console" and "Console 2" Layout. The wheel will be visible in the build menu sometimes. I hope this does not bother you.
