### ISSUE TITLE
EquipWheel broken by Hearth&Home

### ISSUE THREAD

**Issue by ZirconStorm** [virtuaCode/valheim-mods#3]
The EquipWheel mod appears to have broken with the Hearth & Home update. Here's the error log from the console:

> [Error  : Unity Log] MissingMethodException: UnityEngine.GameObject[] EffectList.Create(UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.Transform,single)
> Stack trace:
> EquipWheel.EquipWheelUI.OnEnable () (at <de8f459a9f2b4cec99dc35ec72a44b39>:0)
> UnityEngine.GameObject:AddComponent()
> EquipWheel.EquipGui:Awake()
> UnityEngine.GameObject:AddComponent()
> EquipWheel.Patcher:Awake_Postfix()
> Player:DMD<Player::Awake>(Player)
> UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
> Game:SpawnPlayer(Vector3)
> Game:UpdateRespawn(Single)
> Game:FixedUpdate()

**Comment by IoannisK746** [comment]
Please fix it!! Many relying on this!!!!!

**Comment by virtuaCode** [comment]
Thanks for the bug report. I will look into it today and fix it as soon as possible!

**Comment by virtuaCode** [comment]
Should be fixed in the new version (1.3.5).
