### ISSUE TITLE
Mod Support Help. Magic Overhaul incompatible?

### ISSUE THREAD

**Issue by CaptnAlister** [virtuaCode/valheim-mods#5]
Hello, I'm new to using Github.

And I had a question about this EmoteWheel Mod. Would it work with the Magic Overhaul Mod made by KGvalheim?
Found here: https://valheim.thunderstore.io/package/KGvalheim/MagicOverhaul/

I had these installed, but found when I would try to use the Emote Wheel with the Magic Overhaul mod installed, nothing would happen. The character would move to face where the camera would be pointed but other than that? The character would not animate the selected Emote.

Is there something I've done wrong with trying to use these 2 mods?

**Comment by virtuaCode** [comment]
Yes it's incompatible with Magic Overhaul. The mod author confirmed it too:
![ptOjoVw](https://user-images.githubusercontent.com/16387293/140033903-d6cef35e-3ee2-4e8b-94ce-66fa7805887e.png)
:

**Comment by CaptnAlister** [comment]
> Yes it's incompatible with Magic Overhaul. The mod author confirmed it too: ![ptOjoVw](https://user-images.githubusercontent.com/16387293/140033903-d6cef35e-3ee2-4e8b-94ce-66fa7805887e.png) :

Ah I see. Well thank you for clearing that up for me. I suppose I should've dug a little deeper.
