### ISSUE TITLE
Equip Wheel: Name Filtering Request

### ISSUE THREAD

**Issue by lightsourced** [virtuaCode/valheim-mods#6]
I'm wondering if the functionality by filtering by names with * can be added to add any item with a portion of that word in the name to the wheel. For example, adding * axe * (had to put spaces here for formatting reasons) to name filter will add Magic Axe and Axe of the Defender to the wheel. I tried it on my end and didn't seem to work out of the box. Thanks!

**Comment by virtuaCode** [comment]
The new version 1.5.0 supports regex filtering when `ItemFiltering = true` is set in the config.
For example you can use `ItemRegex = ( axe)|(axe )` to filter for axes.
