### ISSUE TITLE
mistlands PTB (in)compatibility

### ISSUE THREAD

**Issue by lauren-mods** [virtuaCode/valheim-mods#8]
Hi,

When using your mod on the public test beta for mistands, I get this error:

```
MissingMethodException: void Humanoid.RemoveFromEquipQueue(ItemDrop/ItemData)
  at (wrapper dynamic-method) InventoryGui.DMD<InventoryGui::UpdateItemDrag>(InventoryGui)
  at InventoryGui.Update () [0x0026e] in <035307060cbb4b30b916cd82ebd80490>:0 
```

Thought you might like to know as I expect this will happen when the patch goes live!

Will post my full log in a reply post in case that's helpful.
Lauren :)

**Comment by lauren-mods** [comment]
Full log:

[Player.log](https://github.com/virtuaCode/valheim-mods/files/10148905/Player.log)

**Comment by virtuaCode** [comment]
Thanks for the bug report. A renamed function is causing the issue. I will publish a fix when the Mistlands Patch is officially released.
